### ISSUE TITLE
Baubles Inventory and NEI Item Subsets

### ISSUE THREAD

**Issue by Thiana** [Azanor/Baubles#105]
For some reason the NEI Item Subsets don't work from within the Baubles inventory. They do work without issue from the standard inventory. From looking at the Minecraft forums, this bug appears to have been around since at least Aug 2014.

NotEnoughItems-1.7.10-1.0.5.110-universal
Baubles-1.7.10-1.0.1.10

**Comment by Azanor** [comment]
That is something for NEI to solve.
