### ISSUE TITLE
The file Babubles gets removed at start on both my client and server? 

### ISSUE THREAD

**Issue by Hund** [Azanor/Baubles#107]
So.. I noticed that everytime I start my client and my server the Baubles mod gets deleted!? How? And why? I even changed ownership to root and only read permission for the others, that didnt help. To clarify, Im not running anything as root.

This is freaking me out. Im running my own modded Forge server.

**Comment by gigabit101** [comment]
Baubles gets moved to the 1.7.10 folder inside of your mods folder

**Comment by Hund** [comment]
I noticed that. I felt so stupid when I figured it out. :(
