### ISSUE TITLE
Baubles do not work in LAN

### ISSUE THREAD

**Issue by LordSaad44** [Azanor/Baubles#110]
So I got botania baubles and the aura band, the mana band, AND souljours sash all aren't working. Funny enough, same problem happened with thaumcraft baubles.

I can confirm this is indeed a bug, I've googled the issue and a few people have it and all where open to LAN and playing with there friends. The baubles can be placed in the bauble slots just fine, they just do NOTHING. Absolutely NOTHING. Even after charging my aura band manually, my souljour sash stayed kaput.

**Comment by trollworkout** [comment]
lan has huge issues skins dont work and minetweaker doesnt work. seems to be a forge/minecraft issue.

**Comment by Azanor** [comment]
Does this problem still happen?
