### ISSUE TITLE
baubles and Witchery compatibility

### ISSUE THREAD

**Issue by Bellwar** [Azanor/Baubles#113]
I saw on botania reddit question if he can get his relics i think mainly the ring of loki, anyway here is the link on that reddit: https://www.reddit.com/r/botania/comments/3lno03/botania_recovering_lost_relics/?ref=share&ref_source=link

But his problem was the boubles not getting dump out after he went there, this also break the witchery idea.
So i dont know if you can fix it at all or it is witchery side but its a thing.

**Comment by trollworkout** [comment]
no api he cant do it. witchery needs to support baubles
