### ISSUE TITLE
1.8.8 Exception - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by DementedCin** [Azanor/Baubles#118]
Forge Version: 1.8.8 - 11.15.0.1654

Package: baubles.common.container
Class: ContainerPlayerExpanded
Method: onContainerClosed(EntityPlayer player)
Line: 110 (approx)

The method "removeStackFromSlot" is used but is not defined in the forge api, which results in an exception being thrown at run time.

It would appear that the api now defines the method as "getStackInSlotOnClosing" which returns the stack at the index after setting the index to null.

**Comment by GirafiStudios** [comment]
When does this happen?

**Comment by DementedCin** [comment]
It occurs for me when you have equipped an item and then try and close the inventory screen.

**Comment by Azanor** [comment]
Is this happening in a dev environment or something?

**Comment by PrinceOfAmber** [comment]
In forge 1.8.9 it is called removeStackFromSlot, but in 1.8.8 it was getStackInSlotOnClosing

**Comment by Azanor** [comment]
This should be fixed in the latest baubles version.
