### ISSUE TITLE
No Baubles-deobf-1.1.1.0.jar found

### ISSUE THREAD

**Issue by Enderborn1235** [Azanor/Baubles#119]
I am currently making an addon for Thaumcraft 5.0.3, but when I try to run it an error occurs saying, "DepLoader was unable to download required library Baubles-deobf-1.8-1.1.1.0.jar Check your internet connection and try restarting or download it manually from https://dl.dropboxusercontent.com/u/47135879//Baubles-deobf-1.8-1.1.1.0.jar and put it in your mods folder". I have an internet connection, and I tried to download it manually by following the link, but I was met with a 404 error when at the Dropbox link. Help me please, I am new at this.

**Comment by GirafiStudios** [comment]
https://www.dropbox.com/s/w5agc4ytotqfiob/Baubles-1.8-1.1.1.0.jar?dl=0

**Comment by Enderborn1235** [comment]
nevermind, found another download, all is well
