### ISSUE TITLE
Dropbox 404.

### ISSUE THREAD

**Issue by ryantheleach** [Azanor/Baubles#120]
Previous versions of deobf are missing for baubles. I was trying to test something in thaumcraft for 1.8, but it attempted to download baubles from a dropbox which gives a 404.

**Comment by Azanor** [comment]
which one was it trying to download?

**Comment by ryantheleach** [comment]
I don't need it anymore, the issue was resolved another way, but for reference it was the baubles required for Thaumcraft-deobf-1.8-5.0.3 . I've somehow messed up my dev workspace so I'm unable to tell you the exact version as I can't get minecraft to launch.

**Comment by ryantheleach** [comment]
Downloading file https://dl.dropboxusercontent.com/u/47135879/Baubles-deobf-1.8-1.1.1.0.jar
