### ISSUE TITLE
Corrupted baubles inventory, hoping for a quick delete command or name of the file

### ISSUE THREAD

**Issue by Trisscar05** [Azanor/Baubles#122]
Hi, just popping over from the Ag Skies 2 github with a question. Is there a way to delete a player's baubles inventory using commands, or a certain file somewhere that can be deleted and regen'd?
Reason being this issue:
https://github.com/jadedcat/AS2Configs/issues/207

**Comment by Azanor** [comment]
Nope, no command. Dying should do the trick however as the items should simply drop to the ground.
