### ISSUE TITLE
[1.8.9] Baubles Inventory being Cleared on Logout

### ISSUE THREAD

**Issue by MastaC729** [Azanor/Baubles#128]
Forge version: 11.15.1.1855
Baubles version: 1.1.3.0

Whenever someone logs off of the server and reconnects, their Baubles inventory is completely cleared.

Not sure if this issue is an oversight on my part or a bug.

**Comment by mrdeadlocked** [comment]
We're having the same issue on version 1.2.1.0 and forge 12.17.0.1936.

**Comment by mrdeadlocked** [comment]
I have noticed if you log off and on a few times your baubles do come back.

**Comment by Azanor** [comment]
Should be solved with latest 1.3 beta version
