### ISSUE TITLE
Packet handlers not thread safe

### ISSUE THREAD

**Issue by williewillus** [Azanor/Baubles#134]
All of baubles' packet handlers currently process on the network thread. This is dangerous behaviour and will cause the classical host of threading issues associated with touching the game thread from elsewhere.

Everything needs to be wrapped into `Minecraft.getMinecraft().addScheduledTask(new Runnable() { <actual handler here>)`

This affects all versions for 1.8.0+

**Comment by Azanor** [comment]
The provided code doesn't actually work (causes a crash server side), but I get what you mean.

**Comment by williewillus** [comment]
Oh yeah the code in the comment is for client bound packets.
For server bound packets it's `ctx.getServerHandler().playerEntity.mcServer.addScheduledTask()`
