### ISSUE TITLE
Main bauble handling is unsafe and broken

### ISSUE THREAD

**Issue by williewillus** [Azanor/Baubles#135]
Currently there is a static `Map<String, InventoryBaubles>` tracking player bauble inventories.
There's some unsafe things about it:

1. UUIDs need to be used instead of strings
2. It's static. This is a HUGE issue in the single player integrated server because you have the client and server threads running all over each other's toes trying to update what is actually the *same* object because the two threads are in the same VM. The client EntityPlayerSP and server's EntityPlayerMP need to have different objects.
3. That second claim can be backed up by many modders that have included baubles integration. It also the most likely cause of issues regarding baubles being erased, lost, or otherwise corrupted (along with #134)

Ideally, baubles should be moved to the [Capability system ](https://gist.github.com/williewillus/c8dc2a1e7963b57ef436c699f25a710d). which are like the old IEEPs and are attached per player.

**Comment by Azanor** [comment]
Should be solved with latest 1.3 beta version
