### ISSUE TITLE
Bauble Slot Duplicates Botania Mana Rings

### ISSUE THREAD

**Issue by Darkosto** [Azanor/Baubles#137]
Hello
I believe this is a baubles glitch, but I can reproduce duplicating the Band of Mana and the Greater Band of mana 100% of the time.

Have a band of mana (Needs to have mana in it, I've been testing with almost full mana) in your first ring slot and a botania sash in the 3rd slot (You don't need anything else but could have inventory/armor and it will still work)
Die from wither damage and don't move around or have inventory open
You will respawn with the band of mana in your bauble slot while the rest of your items are in a grave or on the ground including the band of mana that dropped when you died
I managed to fill 5 mana pools in the span of 5 minutes with this duplication glitch.

I'm using 1.7.10 mc, forge 1614 and Botania r1.8-249, and baubles 1.0.1.10

I'm working on completing the next update of Sky Factory and would like to include an update if possible.

Thank you very much!!
Darkosto

**Comment by Azanor** [comment]
Closing this for now - if it reoccurs with the new 1.3 versions then please feel free to reopen
