### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by jeep70** [Azanor/Baubles#141]
My friend said that he clicked on a lava charm (from random things) and picked it up with his cursor, clicked on the button to switch to baubles inventory, and the server crashed.

**Comment by GirafiStudios** [comment]
Please provide what version of Minecraft, Forge and Baubles you are using :)

**Comment by jeep70** [comment]
Oh, I forgot to leave the crash log http://pastebin.com/t3j0sd5m

**Comment by Azanor** [comment]
Thanks, I'll take a look

**Comment by Azanor** [comment]
I'm unable to duplicate this problem. It does not directly seem baubles related anyway. I am testing against the 1.3 version of baubles though, so it might have fixed itself without me knowing :)

Closing this for now, but please reopen if it occurs again in the newer versions.
