### ISSUE TITLE
Baubles not found by Botania

### ISSUE THREAD

**Issue by Mattsingen** [Azanor/Baubles#142]
Not sure if the issue is in Botania or Baubles but I guess that it comes from the change in MODID from Baubles to baubles on the September 22 commit.

@Vazkii

**Comment by Vazkii** [comment]
Cpw has already confirmed there's no need to change mod IDs mid version. Please don't as you'll break dependencies.

**Comment by Azanor** [comment]
Well, since there was API changes as well I thought it would be a good time to lowercase the id as well.

Strange though, I tested baubles with a few other mods like ender-io that has baubles integration and didn't run into any issues. I guess it doesn't have baubles as a dependency?
