### ISSUE TITLE
[1.3.BETA5] Crash on world start

### ISSUE THREAD

**Issue by SPMoo66** [Azanor/Baubles#143]
Game crashes on world generation/load. Not entirely sure why. Crash either points to something about baubles or botanical addons... which isn't one of the mods I have. It's not even available for 1.10.2.
So uh... this might be for you?

http://pastebin.com/A8nrB0qs

**Comment by GirafiStudios** [comment]
As you can see on line 169 Natural Pledge is using "botanicaladdons" as its modid (I guess it was originally called that?). So this is a problem with Natural Pledge, since it is using a class from Baubles that got removed in the 1.10.2 update :)

**Comment by SPMoo66** [comment]
I had no idea Natural Pledge was related to Botanical Addons, guess I'll report it to them. Thanks for the help!

**Comment by Azanor** [comment]
They really should not have been using classes not exposed by the API. Very naughty.
