### ISSUE TITLE
[feature request] Allow option for a single bauble to fit into any of the slots

### ISSUE THREAD

**Issue by PrinceOfAmber** [Azanor/Baubles#146]
I was wondering if its possible to allow one item to go into any of the four slots.  Or if not, is that a feature you are willing to do.

I know this might be complicated, or you might not want to support it, its just a feature that would be nice to have.

In the function

` public BaubleType getBaubleType`

I return just one type, and that defines what slots it goes into.  Maybe if that returned null it could go into any slot?  Or add a new enum type BaubleType.ALL so it could go into any ?

**Comment by Azanor** [comment]
Something like this is possible, but a fairly big change to the API. If I implement something like this it would probably have to wait for the next big release - probably along with MC 1.11

**Comment by Azanor** [comment]
Yup, one of the changes for the 1.10 version has made doing this very easy. Expect something in the next 1.3.beta7 release.

**Comment by PrinceOfAmber** [comment]
Hey, im excited for this feature, (downloaded BETA7), but when I return type TRINKET, i cant equip the items.  In older builds with type RING or others they equipped.  Is this a bug or im doing something wrong?

https://github.com/PrinceOfAmber/Cyclic/blob/053416bfdcd08ea79580727da2782767e646d6c0/src/main/java/com/lothrazar/cyclicmagic/item/BaseCharm.java#L69

Honeslty i didnt know java enums could have multiple values.  I expected it to be TRINKET(4) instead of TRINKET(0,1,2,3) . but if it was 4 you would have to change
	public boolean hasSlot(int slot) {
		for (int s:validSlots) {
			if (s == slot) return true;
		}
		return false; 
	}
