### ISSUE TITLE
Crash with newest Beta version 

### ISSUE THREAD

**Issue by jonabrv1965** [Azanor/Baubles#147]
Hello, to report a crash when loading my existent world (MC loads ok to the main menu). Using Baubles-1.10.2-1.3.BETA5.jar. Reverting to version Baubles-1.9.4-1.2.1.0, the world loads ok.

[crash-2016-10-06_08.51.43-client.txt](https://github.com/Azanor/Baubles/files/513919/crash-2016-10-06_08.51.43-client.txt)

**Comment by SPMoo66** [comment]
You have Natural Pledge installed too, that's the problem

#143

**Comment by Farronox** [comment]
Experiencing the same issue. Release version works, although experiencing large lag, still debugging that, but previous betas are not appearing as compatible with Botania.

http://pastebin.com/SJhq8jwS

**Comment by Azanor** [comment]
This is a problem on Botania's side - instead of using the API, they access Baubles classes directly. Classes which now no longer exist. You guys might want to go report it there.

**Comment by jonabrv1965** [comment]
Thanks Azanor, will do, regards!

**Comment by Azanor** [comment]
I keep bloody having to reopen this.

**Comment by jonabrv1965** [comment]
:-), I've found another issue with the latest versions of Baubles, although not your fault, it is affecting me (and I guess a bunch of fellow minecrafters) : the Baublesstuff mod (https://minecraft.curseforge.com/projects/baubles-stuff?gameCategorySlug=mc-mods&projectID=236988) which contains very very very useful trinkets, crash with your "beta" releases. I (and several others) already report this to the baublesstuff author,  but he seems not available.... for now I'll keep your version Baubles-1.9.4-1.2.1.0 in my pack till figure out a solution... ;-)

The price for be so popular and useful!!!! :-) :-)

[crash-2016-10-11_22.32.59-server.txt](https://github.com/Azanor/Baubles/files/524991/crash-2016-10-11_22.32.59-server.txt)

**Comment by jonabrv1965** [comment]
Ah, by the way, Vaskii released a new version of botania (Botania r1.9-330.jar)... still crashes with your BETAs... so I ban botania from my pack... not that useful at the end...

**Comment by GWSheridan** [comment]
Get this crash now that i have updated to the new version of Baubles http://pastebin.com/ZVitb8rB

**Comment by GWSheridan** [comment]
Get this crash with Baubles-1.10.2-1.3.BETA11 http://pastebin.com/ivMS6g4E

**Comment by jonabrv1965** [comment]
Hi Azanor,  Sheridan... to inform you that the "baubles stuff" mod is now updated and works fine with the latest version of baubles. One thing less! :-)

**Comment by Azanor** [comment]
Excellent

**Comment by DaFuJosh** [comment]
i got issue with Baubles / Botania r1.9-332
![2016-10-18_11 42 52](https://cloud.githubusercontent.com/assets/22819922/19474750/d74f26e4-9528-11e6-8e76-0994bacc8b53.png)

**Comment by GWSheridan** [comment]
@Azanor @jonabrv1965  tryed it this morning all working perfectly no crashes

**Comment by GirafiStudios** [comment]
@DaFuJosh you need to update Baubles you are using a old version.

**Comment by jonabrv1965** [comment]
Hi all, I just tested botania 3.3.2 with latest Baubles (Baubles-1.10.2-1.3.BETA11) and is working ok. I guess you can close this ticket Azanor :-)

**Comment by CuteFluffy** [comment]
[crash-2016-10-19_22.16.16-client.txt](https://github.com/Azanor/Baubles/files/540084/crash-2016-10-19_22.16.16-client.txt)
[crash-2016-10-19_22.16.15-server.txt](https://github.com/Azanor/Baubles/files/540083/crash-2016-10-19_22.16.15-server.txt)

It still crashes for me with the latest version of forge, botania, baubles and baubles stuff.

**Comment by gigabit101** [comment]
well that first one is mine BaublesHud is not using the new baubles yet the second is project e

**Comment by gigabit101** [comment]
as for me and BaublesHud update to new release on curse
