### ISSUE TITLE
Using the Vanilla End-->Overworld portal deletes bauble inventory

### ISSUE THREAD

**Issue by iPencil** [Azanor/Baubles#154]
We're on 1.10.2, Forge 2094, baubles-1.10.2-1.3.Beta9, with Botania r1.9-330:

When you exit the end using the vanilla portal that appears after slaying the dragon, all your baubles are gone. Relogging/restart didn't fix it. We're on a dedicated server. Previous release build of baubles did not do that.

No error/log/anything to include, but I'm happy to provide additional information if needed.

**Comment by williewillus** [comment]
@azanor: You have to save and restore capabilities on player clone:
https://github.com/sinkillerj/ProjectE/blob/MC1.10.x/src/main/java/moze_intel/projecte/events/PlayerEvents.java

**Comment by Azanor** [comment]
Thanks, I was not aware of that. Will fix.
