### ISSUE TITLE
 Crashes when near cactus and forestry hives

### ISSUE THREAD

**Issue by CrZain1000** [Azanor/Baubles#155]
crash reports indicate baubles is part of the error but also forestry and blood arsenal are within the report too. 

I can't really tell what mod is the real culprit, let me know if I should send the issue to blood arsenal or forestry if its not baubles issue

Crash Report: [crash-2016-10-14_09.20.14-server.txt](https://github.com/Azanor/Baubles/files/529935/crash-2016-10-14_09.20.14-server.txt)
Crash Report: [crash-2016-10-14_10.17.16-server.txt](https://github.com/Azanor/Baubles/files/529936/crash-2016-10-14_10.17.16-server.txt)

**Comment by Alex-hawks** [comment]
This one goes to Blood Arsenal, if you have double checked the version requirements

**Comment by Azanor** [comment]
Related to #147. A lot of mod authors don't seem to understand what an API is and has been accessing Baubles code directly. Code that has now changed and thus breaks.
