### ISSUE TITLE
Erroneous onUnequipped behaviour

### ISSUE THREAD

**Issue by Vazkii** [Azanor/Baubles#156]
https://github.com/Vazkii/Botania/issues/1938

The change to capabilities seems to have broken onUnequipped a bit.

* The ItemStack parameter appears to be always null.
* The method is not called at all if another item is placed in the slot at the same time the item being unequipped is removed.

**Comment by Devintrainer** [comment]
Please fix, Aza!

**Comment by Azanor** [comment]
Thanks, I'll take a look
