### ISSUE TITLE
Crash as Forge finishes loading while using 1.3.Beta9

### ISSUE THREAD

**Issue by Zarepheth** [Azanor/Baubles#157]
When starting MineCraft with Forge and Baubles-1.10.2-1.3.BETA9, MineCraft crashes when loading my world. World loading seems to progress until shortly before I expect the environment to render, then I get a crash to desktop.

[Uploading crash-2016-10-14_19.47.21-client.txt…]()

**Comment by Zarepheth** [comment]
The same error occurs with Baubles-1.10.2-1.3.BETA8. I think I need to revert back to the prior version of Botania and use the release version of Baubles until this is fixed.

[crash-2016-10-14_20.38.28-client.txt](https://github.com/Azanor/Baubles/files/530699/crash-2016-10-14_20.38.28-client.txt)

**Comment by Azanor** [comment]
Already reported and it is a Botania error, not Baubles. See #147

**Comment by esotericist** [comment]
For clarity, this actually looks like a Baubles Stuff (https://minecraft.curseforge.com/projects/baubles-stuff) error, not Botania. Just so we can point fingers in the right direction.

**Comment by Zarepheth** [comment]
I removed Baubles Stuff (which I thought I had removed weeks ago when I thinned out my mods from well over a hundred to mere 80). After loading the world, confirming past Forge's warning about 50 blocks being removed from the game, eventually Forge did remove the offending blocks from Baubles Stuff, then crashed with a Java Access violation. I backed down from Forge-1.10.2-12.18.2.2107 to Forget...2106 and tried again. This time the World loaded with no errors - and I was able to play for a couple hours.

I'll have to accept @esotericist diagnosis: Bauble Stuff was the problem. Though I'm curious were in the crash report the evidence was found... The stack trace only showed Baubles, Forge, Minecraft, and Java calls with "... 15 more" at the end. I'm rather curious about what was actually in those "... 15 more".

**Comment by esotericist** [comment]
> Though I'm curious were in the crash report the evidence was found... 

Right here:

`java.lang.NoClassDefFoundError: baubles/common/lib/PlayerHandler
	at md.zazpro.mod.common.baubles.Ring_Core.clientTick(Ring_Core.java:97)`

Zazpro is the Baubles Stuff author.
