### ISSUE TITLE
Crashing Taking Damage, Sometimes Clicked for Taking Damage.

### ISSUE THREAD

**Issue by KaneHart** [Azanor/Baubles#159]
Not sure what is going on or what mod is doing it I feel like it's more then one but it seems I crash/kicked when taking damage. Fall Damage, lava, explosions, etc. Even in creative If I take damage but not actually take it I crash.

http://pastebin.com/1rVXhhHe

**Comment by Azanor** [comment]
This is a problem with the bloodarsenal mod (whatever that is). It is not implementing the Baubles API correctly.
