### ISSUE TITLE
Possible mod conflict with Blood Arsenal

### ISSUE THREAD

**Issue by ariosos** [Azanor/Baubles#160]
With Baubles and Blood Arsenal installed, any mob can not be hit. Simply go up to any mob (passive or hostile) and try to hit it.

Also, if I remove Baubles, it works fine. If I remove Blood Arsenal and leave Baubles, it also works fine.

Baubles-1.10.2-1.3.BETA11
BloodArsenal-1.10.2-2.0.1-13
BloodMagic-1.9.4-2.1.0-65
Guide-API-1.10.2-2.0.2-45

Forge version 2107

**Comment by Azanor** [comment]
Very strange. Baubles does not even come close to modifying any code that would impact combat or do something you describe.

**Comment by ariosos** [comment]
Yeah, maybe it's on Blood Arsenal's end. Can't find their issue tracker though. :/

**Comment by GirafiStudios** [comment]
There issue tracker is right here: https://github.com/Arcaratus/BloodArsenal :)
