### ISSUE TITLE
[request] one new slot

### ISSUE THREAD

**Issue by ArtixAllMighty** [Azanor/Baubles#162]
So, instead of making my own inventory, which I did when I started to make my mod a few years ago, I now have decided to switch over to baubles. (many people asking for that).

I myself added a body slot, two rings, gloves, and a necklace. which can all be substitued by bauble's types, except for the gloves. I could offcourse change the gloves to something like tiaras or so, but that would be unfun. for me. 

Anyway, i'd love to know wether it would be possible to add glove slots ?

Edit : if you'd like to know what mod i was talking about, here is a link.
https://minecraft.curseforge.com/projects/the-rpg-inventory-and-classarmor-mod#c11

**Comment by Azanor** [comment]
Sorry, but I'm highly unlikely to add any more slots to baubles. You could maybe make the gloves use the charm slot?

**Comment by ArtixAllMighty** [comment]
I'm making the crystal use the charm slot already =/
But i understand you wont add any new ones. I'll figure something. thanks for answering though !
