### ISSUE TITLE
Crash on World creation

### ISSUE THREAD

**Issue by Cuppycake** [Azanor/Baubles#166]
Sorry if this has been posted or if this is a Botania side, if so Ill forward it over there but I could not find anything on this. 

Pack loads fine but the crash happens right as the world generates. 
Baubles-1.10.2-1.30
Botania-r1.9-330

http://pastebin.com/deDyPRgm

**Comment by Azanor** [comment]
You might want to try a fresh version of Forge. I think yours might be corrupt since it seems forge itself is crashing.

**Comment by Cuppycake** [comment]
Tried with a few versions of forge including the latest. Still the same crash log. The world will load with just Baubles and Botania so I'm expecting it's another mod using Baubles. Not 100% sure what else is. Time to delete one by one lol.

**Comment by Cuppycake** [comment]
Found it just in case you come across anyone with this issue again:

Runes Of Wizardy 
https://minecraft.curseforge.com/projects/runes-of-wizardry

**Comment by Cuppycake** [comment]
Turns out it was Reliquary. Sorry about that XD
