### ISSUE TITLE
Bizarre issue causes constant disconnects (urgent)

### ISSUE THREAD

**Issue by banjomarx** [Azanor/Baubles#172]
This may or may not be related to the other blood arsenal issue....note that this issue does NOT cause a crash, instead it constantly forcibly kicks me... i pulled this from the server console
- edit 
erm srry i was half asleep at the time, 
this is using the most recent baubles (1.33) on minecraft 1.10.2 with  Forge 12.18.1.2095  and it occurred after i walked into lava for some reason, im completely naked and using no items in creative mode
http://pastebin.com/Byigah8Q

**Comment by banjomarx** [comment]
erm srry i was half asleep at the time, 
this is using the most recent baubles (1.33) on minecraft 1.10.2 with  Forge 12.18.1.2095

**Comment by banjomarx** [comment]
updated the initial claim to make life easier for you

**Comment by Azanor** [comment]
It seems to be a problem with BloodArsnenal, not Baubles itself.

**Comment by bloodyraoul** [comment]
I have the same kind of issue, unable to connect to server or kicked immediatly with Bauble 1.3.5 and JustEnoughResource 5.7.87
If I rollback theses two mods to previous version, it works.
I dont know if it is the same bug or incompatibility between the 2 mods

**Comment by Azanor** [comment]
Looked at the crashlog given again and it is defintely a problem on bloodarsenals side - it is making direct calls to a class that does not exist anymore instead of using the baubles api like it should. So in short - not my problem.

@bloodyraoul crash logs would be handy - it might not be the same problem as above.

**Comment by bloodyraoul** [comment]
Unfortunetly, I dont have any crashlog, i am just disconnected

**Comment by Luke-Thompson** [comment]
@bloodyraoul just give him the game log, though check with the latest versions to see if it's fixed first.

**Comment by bloodyraoul** [comment]
The last version fix my problem, thank you

**Comment by Azanor** [comment]
Good to hear :)
