### ISSUE TITLE
[1.10.2] crashes in logs connecting to servers

### ISSUE THREAD

**Issue by b0bst3r** [Azanor/Baubles#173]
http://pastebin.ubuntu.com/23480823/ - do a search for "at baubles" or scroll to the end.

Baubles-1.10.2-1.3.4

This sometimes stops me from connecting to my server.

**Comment by Azanor** [comment]
Very strange - the error should in theory not be possible. It looks like your player is somehow being ticked without the world actually having finished loading yet. I suspect some other mod or plugin might be messing with it. Either way I will build in a check for it even though it should not be possible.
