### ISSUE TITLE
Crash after updating baubles to 1.3.7

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/Baubles#180]
[crash-2016-12-07_21.07.46-client.txt](https://github.com/Azanor/Baubles/files/637668/crash-2016-12-07_21.07.46-client.txt)

**Comment by Elvarion** [comment]
Baubles-1.10.2-1.3.7.jar
[crash-2016-12-07_23.23.38-client.txt](https://github.com/Azanor/Baubles/files/637900/crash-2016-12-07_23.23.38-client.txt)

Baubles-1.10.2-1.3.6.jar
works just fine

**Comment by sandalle** [comment]
[crash-2016-12-07_15.08.13-client.txt](https://github.com/Azanor/Baubles/files/637978/crash-2016-12-07_15.08.13-client.txt) after updating Baubles for [Modderation: Frostburn](https://github.com/sandalle/ModderationConfigs/tree/frostburn) to 1.10.2-1.3.7 as well, using Forge 12.18.3.2185.

I removed OptiFine in case that was causing the issue, but the problem persisted until I downgraded the client to 1.10.2-1.3.6.

**Comment by Luke-Thompson** [comment]
Also having this issue when I try to join a server. Running single player works fine though. Server did not crash, only client. (ticking entity)
