### ISSUE TITLE
[Suggestion] Capabilities for IBauble

### ISSUE THREAD

**Issue by darkhax** [Azanor/Baubles#183]
While the Baubles API already uses Capabilities for the inventory, it would be very beneficial for devs if IBauble used the capability system as well. By doing this, devs who use the API would have much greater control over how items become an IBauble. For instance, with the CapabilityAtatchEvent, the dev could give an item like the Elytra an IBauble. Currently mods such as PortableJim's [Angel Ring To Bauble](https://minecraft.curseforge.com/projects/angel-ring-to-bauble) use substitution to complete this, however this is a less than ideal solution.

**Comment by Azanor** [comment]
Only merged with the 1.11 branch for now.
