### ISSUE TITLE
Duplication Bug With Inventory Sorter Mod

### ISSUE THREAD

**Issue by Darkosto** [Azanor/Baubles#184]
Hello!

While using middle-click inventory sort with the Inventory Sorting mod by CPW on items in Bauble Slots, baubles are duplicated and inserted into the player inventory. Make sure to have at least 2+ other items (i.e. cobblestone) in your inventory when doing this or else the duplication will not happen.

Video of dupe: https://sx.artdude.uk/hotlink-ok/darkosto/5Ql7-2f4fd-1484438050.mp4

Baubles: 1.3.8
Inventory Sorter: 0.10.3+44
Minecraft: 1.10.2
Forge: 2209

Thank you for taking a look at this :)
Darkosto

**Comment by cpw** [comment]
Fixed it on my end, sorry for  the noise Azanor. Your inventory mapping layout is weird though, and slot indexes were not where I expected.

**Comment by Azanor** [comment]
Cool :)
