### ISSUE TITLE
Baubles Crash Issue

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [Azanor/Baubles#190]
Hello, I am having a crashing issue because of the mod Aura Cascade, but since it has been a couple days since hearing no word from its maintainer, I thought I might look for an alternative solution here.

Because of a bauble added by Aura Casade, my world crashes upon loading.  Is there a way to clear my baubles inventory without being ingame? I cannot use /kill because of the instant crash, I cant open the world to LAN and have someone else kill me, and deleted player data yielded no results. As such I think some sort of failsafe to delete all baubles would be beneficial

**Comment by Azanor** [comment]
Are you using the latest 1.10 & 1.11 versions of baubles? If so then you are out of luck unfortunately unless you don't mind deleting your player savefiles.
