### ISSUE TITLE
1.10.2 - Can't drop items /w simple magnet

### ISSUE THREAD

**Issue by HellishINC** [Azanor/Baubles#191]
Not sure which mod is responsible. If it's SM, please close and disregard.

Whenever I try to drop an item I get the following error:
https://gist.github.com/HellishINC/9d3d8ad622f8f5d2eaf92c9c6639f7d1

Baubles-1.10.2-1.3.9.jar, Forge 2254

Removing Baubles or Simple Magnet allows me to drop items once more.

**Comment by GirafiStudios** [comment]
This is a Simple Magnet issue. They are using a version of Baubles that is at least half a year old.

**Comment by HellishINC** [comment]
Understood. Closing this as it's on them.
