### ISSUE TITLE
Opening up inventory in survival mode in dev workspace crashes game

### ISSUE THREAD

**Issue by Nuclearsmilz** [Azanor/Baubles#200]
[The crash](https://pastebin.com/sZtThZ0r)

Baubles Version: 1.11.2-1.4.3
Forge Version: 1.11.2-13.20.0.2296

It's really quite annoying because my computer takes a long time to load minecraft so when it crashes to open inventory...you can see why it'd suck.

**Comment by Xalcon** [comment]
update to baubles 1.4.4
