### ISSUE TITLE
Crash in dev environment upon accessing inventory in survival

### ISSUE THREAD

**Issue by Sunconure11** [Azanor/Baubles#201]
https://pastebin.com/4dMSikE9

Possible relevant file: https://github.com/Um-Mitternacht/Witchworks/blob/1.11.2/build.gradle

As well as: https://github.com/Um-Mitternacht/Witchworks/blob/1.11.2/gradle.properties

**Comment by Azanor** [comment]
You are not using the latest mappings I think. Try updating your mappings, or import baubles as a library instead.
