### ISSUE TITLE
Texture broken

### ISSUE THREAD

**Issue by wenlfs** [Azanor/Baubles#213]
The Miner's Ring texture is broken.

I'm using the 1.10.2 version, is broken since some versions ago.

**Comment by IBeCrayZ** [comment]
This is a known issue and is fixed but I don't think updates/pull requests can be pushed through without azanor's manual input. He's on hiatus atm and busy with life but he said he'd update baubles occasionally so it's a matter of waiting I think.

**Comment by wenlfs** [comment]
I thought that was it. Thank you for answered.
