### ISSUE TITLE
Random crash in a dev environment on 1.11.2

### ISSUE THREAD

**Issue by Sunconure11** [Azanor/Baubles#215]
https://pastebin.com/yqnCRanP

Happened when I tried to view my inventory in survival. Using stable_32 mappings.

**Comment by Azanor** [comment]
Did you manage to solve this?

**Comment by Sunconure11** [comment]
No.

**Comment by Xalcon** [comment]
I just tried the 1.12 version of baubles in my dev environment and works just fine, i used `deobfCompile` though.
I'm using the curseforge maven for this:
```repositories {
    maven { url = "https://minecraft.curseforge.com/api/maven/" }
}

dependencies {
    deobfCompile "baubles:Baubles:1.11:1.4.6"
}```

just replace the versions accordingly :) then run setupDecompWorkspace + IDE setup and you are fine (re-import build.gradle, `idea` task, `genIntellijRuns` task or whatever else you used to setup the project :) )

**Comment by Sunconure11** [comment]
It's an issue relating to stable_32 mappings on 1.11.2.

**Comment by Xalcon** [comment]
Its working just fine for my 1.11.2 dev workspace. Are you using the latest forge version?
![image](https://user-images.githubusercontent.com/5042450/28840857-9e661ede-76f8-11e7-8b99-0c08c4ef1dda.png)

**Comment by Sunconure11** [comment]
I'll switch the forge version soon, the other coder does not like it when I switch forge versions randomly. Maybe that'll fix this.

**Comment by Sunconure11** [comment]
Alright, I'll check now, I've switched the forge version to a newer one, I was using 2388.
