### ISSUE TITLE
Change mcmod.info file to properly show modid. (1.11+)

### ISSUE THREAD

**Issue by TheUnderTaker11** [Azanor/Baubles#216]
![capture](https://user-images.githubusercontent.com/16872377/28439492-c0c4928e-6d67-11e7-99af-6823943e8f39.JPG)
In 1.11.2 lowercase modid is enforced, so of course the actually modid is just "baubles", but in the mcmod.info file it says it is still "Baubles". Just a quick and easy change to stop any possible confusion.

**Comment by Xalcon** [comment]
this was fixed, its just not released yet. It also doesnt break anything (other than the info in the mods list screen).

**Comment by TheUnderTaker11** [comment]
Alright, I knew it was a "Nit picky" thing or whatever you wanna call it, just thought I would bring it to attention if it wasn't known.
