### ISSUE TITLE
No integration with Tool Belt Mod?

### ISSUE THREAD

**Issue by Nexusdog** [Azanor/Baubles#218]
I've used both mods in 1.10.2 so querying whether this is an oversight or yet to be implemented?

[Toolbelt](https://minecraft.curseforge.com/projects/tool-belt)

**Comment by Nexusdog** [comment]
Sorry, that was in reference to the latest 1.12 build

**Comment by Xalcon** [comment]
see https://github.com/gigaherz/ToolBelt/issues/12

**Comment by Nexusdog** [comment]
Thank you for the heads up!
