### ISSUE TITLE
[1.12] Clicking baubles with item on cursor deletes item

### ISSUE THREAD

**Issue by ejektaflex** [Azanor/Baubles#223]
Hello,

I seem to have run into a small bug. When picking up an item with the cursor and clicking on the Baubles icon, the item being held by the cursor gets deleted. This can be reproduced with just Forge and Baubles.

Minecraft 1.12
Minecraft Forge 14.21.1.2443
Baubles 1.12-1.5.1

**Comment by Azanor** [comment]
The item does not actually get deleted - it is simply dropped on the ground which is the default MC behavior.
