### ISSUE TITLE
Dropbox links are broken

### ISSUE THREAD

**Issue by felipeleite5w** [Azanor/Baubles#228]
I read that you corrected the problem, but I continues when a player try to download my modpack...

**Comment by Azanor** [comment]
Could you give more details? What exactly is happening?

**Comment by felipeleite5w** [comment]
![image](https://user-images.githubusercontent.com/30333987/30343364-b3cef06a-97d3-11e7-849c-d84ef1944ad1.png)

**Comment by felipeleite5w** [comment]
that is happening when someone tries to download my modpack

**Comment by Azanor** [comment]
I fixed the manual download links, but I have been unable to solve the deploader issue. You need to include Baubles in your modpack for now and not rely on the deploader to download it.

**Comment by felipeleite5w** [comment]
Could you be mor expecific because I couldnt understand what you said to me, what I should do to fix this ?

**Comment by GirafiStudios** [comment]
What Azanor is saying, is that you should manually download Baubles on CurseForge (Link to latest 1.7.10 version of Baubles: https://minecraft.curseforge.com/projects/baubles/files/2224857 ).

**Comment by felipeleite5w** [comment]
I have that in my modpack...

**Comment by felipeleite5w** [comment]
![captura de tela 5](https://user-images.githubusercontent.com/30333987/30443148-f2dccfde-9954-11e7-800d-063cc187bd76.png)

**Comment by felipeleite5w** [comment]
What should I do

**Comment by felipeleite5w** [comment]
I know that my modpack doesnt have baubles after the download (that is in technic launcher) so to solve that problem I just have to put Baubles in my modpack, so it doesnt need to download using the dropbox link.

**Comment by felipeleite5w** [comment]
Sorry, it was a question

**Comment by Azanor** [comment]
Yes

**Comment by felipeleite5w** [comment]
Ok, problem solveeed
