### ISSUE TITLE
Dropbox 404 issue for an older Deobf version.

### ISSUE THREAD

**Issue by Sunny-III** [Azanor/Baubles#229]
The deobf version of Baubles for 1.7.10 is missing from Dropbox, and whenever I try to launch a test environment with Thaumcraft, it gives a 404 error.

The version I'm looking for is Baubles-deobf-1.7.10-1.0.1.10.

**Comment by GirafiStudios** [comment]
Similiar to https://github.com/Azanor/Baubles/issues/228
But I guess this is a different problem, since you can't run the normal version of Baubles in a workspace.
The automatic download can not be fixed because of CCL though.

**Comment by Azanor** [comment]
I've added links to the 1.7.10 files in the dropbox forum post.
