### ISSUE TITLE
Optifine Causes GUI issues has since 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Azanor/Baubles#237]
![2017-12-30 12_38_59-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/34456539-94eabb76-ed5e-11e7-9728-302e46f3b86c.png)

**Comment by Azanor** [comment]
This is obviously not a baubles issue - this has something to do with that pokemon mod you have installed.

**Comment by P3rf3ctXZer0** [comment]
@Thutmose I figured linking you to this was the appropriate thing to do.
