### ISSUE TITLE
[1.12.2] Latest Baubles update makes dropped items disappear

### ISSUE THREAD

**Issue by gamma-delta** [Azanor/Baubles#239]
I just updated Baubles to 1.5.2 and when I try to drop an item, it just disappears. No entity, no nothing. I know there isn't some effect picking them up and putting them in an inventory somewhere because I have some droppers running and those work fine, and when I downgraded the items could be dropped again.

I am running a few more mods than Baubles so if you want a list I can give it to you.

Please tell me if you need more info.

**Comment by fatoona** [comment]
Same happend to me. It happens when i had the magnet ring from Botania in a Bauble slot. When i took it out, everything is back to normal. Other magnet items that doesnt go into a bauble slot work normally

**Comment by Azanor** [comment]
I suspect this should be posted on the Botania forum then. I have not changed anything in my code that could cause that.

**Comment by gamma-delta** [comment]
I didn't consider testing the magnet ring, so that's probably the problem. I'll check myself "soon".

**Comment by immaViLLaiN** [comment]
I saw this posted on Botania as well. https://github.com/Vazkii/Botania/issues/2509

Issue is when the magnet ring is in a bauble slot. If the ring is in your inventory, works normally. Other items can be in bauble just fine.

Here is the error from the log window as I was watching it. The game doesn't crash, but I can't open any chests, look at ME terminal or even open satchel.

https://pastebin.com/pcN3dCvW

**Comment by Flanks255** [comment]
This only happens with 1.5.2, in 1.5.1 it all works fine, this has also crashed my server at least once, with the following crashlog: https://pastebin.com/sq0xZrgw

**Comment by Azanor** [comment]
So this is a bug with Botania. They access back-end code that has recently changed on my side. They will need to release a patch.

**Comment by BuggaNoia** [comment]
I have this issue recently several times in a pack, that do not include botania (SevTech Ages 3.0.8). Any suggestions for an other workaround than downgrade to 1.5.1 ?
(Don't know if this issue was closed, because the problem was pointed to botania. In this case: I don't think botania can fix this.)
