### ISSUE TITLE
Crash after updating baubles.

### ISSUE THREAD

**Issue by jc2xs** [Azanor/Baubles#240]
After updating Baubles to latest version my server crashed when one of the players logged in.  Player had Botania baubles on his character.  A reboot of the server and the player was able to get in.  So I'm not sure this can be repeated.

Crash Report:  https://pastebin.com/FFje45TR
Pack is EOD Newcomer version 1.1.0
Mod Versions:
Forge: 14.23.1.2583
Baubles:  1.5.2
Botania:  r1.10.352 - Note this mod wasn't updated in the last pack update.

I hope this helps.

**Comment by Somnioblivio** [comment]
having similar issue.

Server is not crashing, but player is DC'd when attempting to put on the botania Spectator or either of the botania mana bands. The player can log back in but will crash if they open the bauble GUI.

only solution was the NBTEdit/delete the baubel from their playerinfo. I'm not really sure if this is a bauble or botania issue but i hope this helps.

Playing the Direwolf20 1.12 pack on beta version 1.15 from the twitch launcher.

**Comment by Azanor** [comment]
This is a problem on Botania's side. They are accessing back-end, non-api baubles code that have recently changed. I believe they will fix it for their next patch.
