### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoSuchFieldError: CHARM

### ISSUE THREAD

**Issue by fantaphantom** [Azanor/Baubles#244]
Hello, before I say what the issue is, I would like to say that I adore this mod. With that being said, me and my friend are having the same issue when it comes to running Baubles. It seems that we get the error "The game crashed whilst initializing game Error: java.lang.NoSuchFieldError: CHARM". We went through multiple mods to see if they worked. But we discovered that Baubles was the issue. Whenever we run forge without this mod, it works perfectly. However when we use Baubles it crashes. Please respond ASAP.

**Comment by JonoColwell** [comment]
Try downgrading, might be related to #241 

New Baubles seems to hate Botania

**Comment by KasperFranz** [comment]
I think it would help if you added your crashlog :)

**Comment by Zombiella** [comment]
I'm getting the same crash and I've tried using different combinations of versions of Botania and Baubles. :/

Latest crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 5/30/18 5:35 PM
Description: Initializing game

java.lang.NoSuchFieldError: CHARM
	at vazkii.botania.common.item.equipment.bauble.ItemTinyPlanet.getBaubleType(ItemTinyPlanet.java:46)
	at baubles.client.ClientEventHandler.tooltipEvent(ClientEventHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:325)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$486/871947554.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$488/2135441530.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at vazkii.botania.common.item.equipment.bauble.ItemTinyPlanet.getBaubleType(ItemTinyPlanet.java:46)
	at baubles.client.ClientEventHandler.tooltipEvent(ClientEventHandler.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_ClientEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:325)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:575)
	at net.minecraft.client.Minecraft$$Lambda$486/871947554.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$488/2135441530.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:589)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:528)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4485956800 bytes (4278 MB) / 7734296576 bytes (7376 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D3 68 mods loaded, 68 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version              | Source                                        | Signature                                |
	|:----- |:--------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft             | 1.12.2               | minecraft.jar                                 | None                                     |
	| UCH   | mcp                   | 9.42                 | minecraft.jar                                 | None                                     |
	| UCH   | FML                   | 8.0.99.99            | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                 | 14.23.4.2705         | forge-1.12.2-14.23.4.2705.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | biomesoplenty         | 7.0.1.2391           | BiomesOPlenty-1.12.2-7.0.1.2391-universal.jar | None                                     |
	| UCH   | baubles               | 1.5.1                | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UCH   | botania               | r1.10-352            | Botania+r1.10-352.jar                         | None                                     |
	| UCH   | craftstudioapi        | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| UCH   | animania              | 1.4.7                | animania-1.12.2-1.4.8.jar                     | None                                     |
	| UCH   | aquaculture           | 1.6.2                | Aquaculture-1.12.2-1.6.2.jar                  | None                                     |
	| UCH   | babyanimals           | 1.11-2               | BabyAnimals-1.11-2.jar                        | None                                     |
	| UCH   | backpack              | 3.0.2                | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| UCH   | betterfoliage         | 2.1.10               | BetterFoliage-MC1.12-2.1.10.jar               | None                                     |
	| UCH   | bibliocraft           | 2.4.4                | BiblioCraft[v2.4.4][MC1.12.2].jar             | None                                     |
	| UCH   | bonsaitrees           | 1.0.4                | bonsaitrees-1.0.4-b71.jar                     | None                                     |
	| UCH   | cfm                   | 4.2.0                | cfm-4.2.0-mc1.12.2.jar                        | None                                     |
	| UCH   | chameleon             | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCH   | chococraft            | 0.9.1.52             | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
	| UCH   | codechickenlib        | 3.1.8.341            | CodeChickenLib-1.12.2-3.1.8.341-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | cookingforblockheads  | 6.4.36               | CookingForBlockheads_1.12.2-6.4.36.jar        | None                                     |
	| UCH   | cosmeticarmorreworked | 1.12.2-v1            | CosmeticArmorReworked-1.12.2-v1.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCH   | customspawner         | 3.11.4               | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| UCH   | deathcounter          | 1.0.0                | DeathCounter-1.12.1-1.0.0.jar                 | None                                     |
	| UCH   | ptrmodellib           | 1.0.2                | PTRLib-1.0.2.jar                              | None                                     |
	| UCH   | props                 | 2.6.0                | Decocraft-2.6.0_1.12.2.jar                    | None                                     |
	| UCH   | dimensionaledibles    | 1.0                  | DimensionalEdibles-1.12-1.0.jar               | None                                     |
	| UCH   | disenchanter          | 1.6                  | disenchanter-[1.12]1.6.jar                    | None                                     |
	| UCH   | dldungeonsjdg         | 1.11.1               | DoomlikeDungeons-1.11.1-MC1.12.2.jar          | None                                     |
	| UCH   | mocreatures           | 12.0.4               | DrZharks MoCreatures Mod-12.0.4.jar           | None                                     |
	| UCH   | fairylights           | 2.1.2                | fairylights-2.1.2-1.12.x.jar                  | None                                     |
	| UCH   | fastleafdecay         | v14                  | FastLeafDecay-v14.jar                         | None                                     |
	| UCH   | ftfloocraft           | 1.8                  | Floocraft+1.12.2-1.8.jar                      | None                                     |
	| UCH   | foamflower            | 1.12.2-1.0.0.0-beta1 | foamflower-1.12.2-1.0.0.0-beta1.jar           | None                                     |
	| UCH   | jei                   | 4.9.2.196            | jei_1.12.2-4.9.2.196.jar                      | None                                     |
	| UCH   | forestry              | 5.8.0.295            | forestry_1.12.2-5.8.0.295.jar                 | None                                     |
	| UCH   | gardenstuff           | 1.12-2.1.1           | GardenStuff-1.12-2.1.1.jar                    | None                                     |
	| UCH   | gravestone            | 1.10.1               | gravestone-1.10.1.jar                         | None                                     |
	| UCH   | harvest               | 1.12-1.2.6-18        | Harvest-1.12-1.2.6-18.jar                     | None                                     |
	| UCH   | waila                 | 1.8.25               | Hwyla-1.8.25-B40_1.12.jar                     | None                                     |
	| UCH   | infernalmobs          | 1.7.5                | InfernalMobs-1.12.2.jar                       | None                                     |
	| UCH   | jeibees               | 0.9.0.5              | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| UCH   | kleeslabs             | 5.4.10               | KleeSlabs_1.12.2-5.4.10.jar                   | None                                     |
	| UCH   | magicbees             | 1.0                  | MagicBees-1.12.2-3.1.10.jar                   | None                                     |
	| UCH   | malisiscore           | 1.12.2-6.4.0         | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCH   | malisisdoors          | 1.12.2-7.3.0         | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UCH   | memeinabottle         | 2.0.0                | MemeInABottle-1.12.X-2.0.0.jar                | None                                     |
	| UCH   | mmm                   | 1.0.8                | mutatedmobs-1.0.8.jar                         | None                                     |
	| UCH   | naturescompass        | 1.5.1                | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
	| UCH   | nei                   | 2.4.1                | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | getalltheseeds        | 1.12a                | Pam's+Get+all+the+Seeds!+1.12a.jar            | None                                     |
	| UCH   | harvestcraft          | 1.12.2u              | Pam's+HarvestCraft+1.12.2u.jar                | None                                     |
	| UCH   | simplerecipes         | 1.12.2c              | Pam's+Simple+Recipes+1.12.2c.jar              | None                                     |
	| UCH   | placeableitems        | 3.3                  | placeableitems-3.3.jar                        | None                                     |
	| UCH   | xreliquary            | 1.12.2-1.3.4.763     | Reliquary-1.12.2-1.3.4.763.jar                | None                                     |
	| UCH   | roost                 | 1.2.0                | roost-1.12-1.2.0.jar                          | None                                     |
	| UCH   | roots                 | 0.104                | roots-2-0.104.jar                             | None                                     |
	| UCH   | soulshardsrespawn     | 1.12.2-1.0.5-7       | SoulShardsRespawn-1.12.2-1.0.5-7.jar          | None                                     |
	| UCH   | storagedrawers        | 1.12-5.3.5           | StorageDrawers-1.12.2-5.3.6.jar               | None                                     |
	| UCH   | storagedrawersextra   | @VERSION@            | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
	| UCH   | subcommonlib          | 1.2.0.1              | subcommonlib-sublib-1.12.2-1.2.0.4.jar        | None                                     |
	| UCH   | telepads              | $version             | telepads-1.12.2-1.1.0.5.jar                   | None                                     |
	| UCH   | torohealthmod         | 1.12.2-11            | torohealth-1.12.2-11.jar                      | None                                     |
	| UCH   | treechopper           | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| UCH   | twilightforest        | 3.7.424              | twilightforest-1.12.2-3.7.424-universal.jar   | None                                     |
	| UCH   | vending               | 1.12.2-3.0.1.1       | vending-1.12.2-3.0.1.1.jar                    | None                                     |
	| UCH   | waddles               | 0.6.0                | Waddles-1.12.2-0.6.0.jar                      | None                                     |
	| UCH   | weeeflowers           | 1.12.2b              | Weee!+Flowers+1.12.2b.jar                     | None                                     |
	| UCH   | xaerominimap          | 1.15.1.2             | Xaeros_Minimap_1.15.1.2_Forge_1.12.jar        | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
