### ISSUE TITLE
Baubles 1.7.10 Crashes When I Create Worlds

### ISSUE THREAD

**Issue by adn18** [Azanor/Baubles#252]
Hi! I downloaded Thaumcraft 1.7.10 (with Forge 1.7.10). Thaumcraft requires Baubles, so I downloaded Baubles 1.7.10 and put it into the "mods" folder with Thaumcraft. Every time I try to run the Minecraft launcher, everything is fine. It isn't until I click "Create World" on Minecraft Singleplayer when my game crashes with a strange error message that says:

You are using an unsupported version of the game.

The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Exception in server tick loop

I've tried redownloading Baubles, Thaumcraft, and Forge from different websites and it still gives me the same message. I made sure that I am downloading all 1.7.10 versions. I am certain that Baubles is the problem, but I don't know what I'm doing wrong. I normally figure out my own crash problems but this time I need help. Thanks! =)

**Comment by EverNife** [comment]
Send the crash report :D
