### ISSUE TITLE
[Crash] Not sure what is going on

### ISSUE THREAD

**Issue by FluffyDiscord** [Azanor/Baubles#263]
Here is the full log. Not sure what happened.

[latest.log](https://github.com/Azanor/Baubles/files/2116364/latest.log)

**Comment by Geethebluesky** [comment]
Check lines 867 and 872-4.... Your log mentions another mod, ActuallyBaubles, which I suspect might be the cause of your crash.

I'd report this particular problem to ActuallyBauble's author and see what they have to say.
