### ISSUE TITLE
[1.7.10] Crash: NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_82877_b(F)V

### ISSUE THREAD

**Issue by cheesealmighty** [Azanor/Baubles#267]
On multiplayer, served crashed after removing my newly crafted belt(with nothing on). 

Crash log: https://paste.ubuntu.com/p/wDqRj29Vsh/

I'm using most recent version available.

**Comment by Xalcon** [comment]
Baubles is not the mod that caused this crash:

>java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_82877_b(F)V
>\>\>\>**at md.zazpro.mod.common.baubles.Belt_Core.onUnequipped(Belt_Core.java:161**)<<<
>	at baubles.common.container.InventoryBaubles.func_70298_a(InventoryBaubles.java:101)
>	at net.minecraft.inventory.Slot.func_75209_a(Slot.java:93)
>	at net.minecraft.inventory.Container.func_75144_a(SourceFile:232)

According to google, the namespace `md.zazpro.mod.common.baubles` belongs to the mod BaubleStuff, which is causing this crash.

**Comment by cheesealmighty** [comment]
Ah, sorry, I kinda assumed that. I'll bug them for it. Much appreciated.
