### ISSUE TITLE
[Suggestion/request] Ammo Slot

### ISSUE THREAD

**Issue by MokahTGS** [Azanor/Baubles#276]
Can we please have an additional slot created specifically for ammo from ranged weapons?  I'm thinking of arrows, or bullets, or anything that is used as ammo for a ranged weapon.  Ideally, I'd like to see modded ammo support for items like tinkers arrows and bolts, etc.

I don't know if this is possible, but it would be a great addition.

**Comment by Loriborn** [comment]
Wouldn't this be implemented on the individual mod's side? I would imagine the chest or belt slot would be more than capable of holding a bandolier of some kind that mods could implement. Those individual bandolier items could then have their own slots that contain things like ammunition, similarly a quiver or backpack mod.

**Comment by Azanor** [comment]
Yup, that sounds like something another mod should add.
