### ISSUE TITLE
[1.12.2] constantly crashing due to java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by DonovanDMC** [Azanor/Baubles#298]
I've had multiple crashes, usually being java.lang.NoSuchFieldError: HEAD/java.lang.NoSuchFieldError: TRINKET

I can't downgrade because of EnderIO, Thaumcraft, and another mod I forgot needs Baubles 1.5.2.

The mods I had issues with were [The One Probe](https://assets.furry.cool/logs/crash-2019-07-24_20.16.46-client.txt), [The Twilight Forest](https://assets.furry.cool/logs/crash-2019-07-24_20.13.11-client.txt), [Silent's Gems](https://assets.furry.cool/logs/crash-2019-07-24_20.08.37-client.txt), [Draconic Evolution](https://assets.furry.cool/logs/crash-2019-07-24_20.05.10-client.txt), and [Thaumcraft](https://assets.furry.cool/logs/crash-2019-07-24_19.52.36-client.txt).

And once I finally removed all of those, the game [crashed on world login](https://assets.furry.cool/logs/crash-2019-07-24_20.29.29-server.txt).

**Comment by KingLemming** [comment]
It sounds to me like you are including a mod which is also including some Baubles files. It should not be doing that. You should remove that mod.

Sorry I can't narrow it down. :(
