### ISSUE TITLE
The Button in the Inventory Moves When the Player Has a Potion Effect

### ISSUE THREAD

**Issue by yolp900** [Azanor/Baubles#57]
When the player has a potion effect in his inventory the button to go to the botania mod moves to the right:
![baubles w potion effect](https://cloud.githubusercontent.com/assets/8226139/3883555/b45adc56-21a2-11e4-83a9-9ceeefea8b3f.png)

Usually:
![regular baubles inventory](https://cloud.githubusercontent.com/assets/8226139/3883556/b45b94f2-21a2-11e4-981c-0a52b289853e.png)

**Comment by bence98** [comment]
Still seems to happen in 1.1.1.0 in the deobf environment without NEI
