### ISSUE TITLE
Bauables disappear on death

### ISSUE THREAD

**Issue by the-vindex** [Azanor/Baubles#81]
When I die, my baubles are totally gone, not dropped on the ground nor present in player's slots.
This happens randomly, not always, so I'm not sure how to reproduce. Checked with NEI's magnet it doesn't fall somewhere out of sight.

FTB Mage Quest pack
Minecraft 1.7.10
Thaumcraft 4.1.2.4

**Comment by TheJulianJES** [comment]
onEquipped is not called on death  for me @Azanor
