### ISSUE TITLE
[Request] Back / Backpack slot

### ISSUE THREAD

**Issue by FireBall1725** [Azanor/Baubles#85]
Hey Azanor,
Would you ever consider adding a 5th slot for like a back / backpack type thing?  I have a few ideas that would be perfect for that kind of slot.
Thanks,
FireBall

**Comment by Azanor** [comment]
Well, nothing is really preventing you from using one of the existing slots for something like that - for example the TC foci pouch can go in the belt baubles slot.
I'd like to keep baubles fairly simple and currently it has nice symmetry with vanilla armor slots :p

**Comment by FireBall1725** [comment]
yea, it would make since for the thing i want to add to go into the belt slot, but then i wouldn't have my speed and step assist :(
