### ISSUE TITLE
Username change

### ISSUE THREAD

**Issue by SuperSandro2000** [Azanor/Baubles#89]
When you change your username with the new mojang feature from today all items in the bauble slots are gone.
Reason: The items are save in <username>.baub and you need to you the uuid.

**Comment by Vazkii** [comment]
If it's saved to the uuid they won't work in offline mode, you can't win this.

**Comment by SuperSandro2000** [comment]
No way?

**Comment by copygirl** [comment]
Perhaps Baubles should move over to IExtendedEntityProperties on the player entity instead of saving to separate files.

**Comment by quaggaman555555** [comment]
Off topic, but didn't I see you on either Soaryn's or Bacon_Donut's stream last night @copygirl?

**Comment by Azanor** [comment]
Yeah, this is an annoying issue, but a pain to solve - there is no easy win.

Moving the save to the player data itself might be a solution. I remember there being an issue with it on the thaumcraft side, but I can't recall now what the problem was exactly. I will have to re-examine it.
