### ISSUE TITLE
Compatibility issue with Sync due to baubles being... global?

### ISSUE THREAD

**Issue by Deadgye** [Azanor/Baubles#90]
Not sure if global is the correct term to use for this. I believe tinkerer's construct also still exhibits this issue with their knapsack and additional 'armor slots'. My goal is to use the "Sync" mod in conjunction with mods that utilize the Baubles mod. I'm also trying to use OpenBlocks as well, but that should be.. mostly unrelated. The sync mod creates clones of the player that have separate inventories. When I change from my original body to clone 1 my original body's inventory, hotbar, and armor remain on my original character. If I'm playing on a clone and I die, I return to the body of another clone or to my original body. 

The problem is that baubles exist across the original body and all clones, they do not stay with the body they were equip on. The additional resulting problem is that if I die on a clone the bauble will no longer be equipped on the intended body, for it dropped upon death.

I made a fresh instance using MultiMC to confirm the behavior. It was running Minecraft 1.7.10 with Forge 10.13.2.1307. Mods installed were Baubles 1.7.10-1.0.1.10, iChunUtil-4.1.3, Sync-4.0.0, OpenBlocks-1.7.10-1.3-snapshot-556, OpenModsLib-1.7.10.0.6-snapshot-307. I said 'mostly unrelated' in regards to OpenBlocks before because I didn't test if the Baubles are dropped to the floor-- I tested if they are dropped into the OpenBlocks grave that is left behind on death (which they are.)

My fml-client-latest.log file is apparently slightly too big to upload to pastebin, so if you think it's necessary please recommend somewhere for me to upload it ; ;.

**Comment by copygirl** [comment]
Could be solved in the same way as #89, saving the Baubles on the player entity instead of in separate files which are bound to the player account.

**Comment by vadis365** [comment]
sorry, not relevant to this mod - was showing someone this as an example of many mods' custom inventories being hard to cater for.
