### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Simuciokas** [Azanor/Baubles#92]
Log: http://pastebin.com/f1NKUA3d

**Comment by Azanor** [comment]
Hmmm, I'll take a look

**Comment by gigabit101** [comment]
@Azanor it seems to be a change in the new versions of forge

**Comment by Jamerboy** [comment]
Nope, it's actually caused by registering the renders serverside

**Comment by JonnyBrando** [comment]
Jamerboy, when I grab your source and compile it, the server-side works but the client-side crashes with CodeChickenCore and NotEnoughItems.

http://pastebin.com/qUc1Hb65

**Comment by Azanor** [comment]
This has been fixed in the 1.1.1.0 version of baubles. That would teach me to not blindy accept commits and only test them in a single player game  :p
