### ISSUE TITLE
Ability to view other players Baubles

### ISSUE THREAD

**Issue by bookerthegeek** [Azanor/Baubles#99]
Hello and thank you for the wonderful mod / api. I do have a question for you

1. We are on a Server
 * As such, we deal with a lot of grief and theft
 * Sometimes we need to discreetly check what a person has in their inventory
2. So we were wondering if one of the following would be possible
 * Add in an OP'ed only command so that Admins can view / edit another players baubles slots
 * Open the slots to the forge essentials API so it works with /openinv command on servers
 * Some other wonderful idea that you might have that I have not thought of.

Thank you for taking the time to read this.

**Comment by Azanor** [comment]
Good suggestion.

**Comment by evernife** [comment]
Any prevision of this?

**Comment by Azanor** [comment]
No yet, but possibly soon

**Comment by Azanor** [comment]
I didn't implement this fully, but I did add the ability to view and clear a players baubles inventory. That should be more than enough for most use cases.

**Comment by evernife** [comment]
Documentation? (https://github.com/Azanor/Baubles/wiki)

And for what version? (**only for 1.10?**)

**Comment by Azanor** [comment]
Yes, added it in the 1.3.BETA9 build.
Check the changelogs or just type /baubles ingame

**Comment by bookerthegeek** [comment]
Thank you. Those two peons alone will greatly decrease server issues when dealing with theft issues.

**Comment by evernife** [comment]
Is there a mere possibility to add it for 1.7.10 ?
